### ISSUE TITLE
Archive Project

### ISSUE THREAD

**Issue by jbants** [sparkgeo/stac-validator-node#1]
Archive https://www.npmjs.com/package/stac-validator
and point Readme to https://github.com/stac-utils/stac-node-validator

**Comment by brianbancroft** [comment]
James, no one _at all_ is using the npm library. 1 download per week is dependabot

https://www.npmjs.com/package/stac-validator

It might make sense at this stage just to scrub it on the NPM Registry

**Comment by brianbancroft** [comment]
Repo archived
